name: lipfd

services:
  lipfd-server: 
    container_name: lipfd-container
    image: lipfd-image
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME:-devuser}
        USER_UID: ${UID:-1001}
        USER_GID: ${GID:-1001}
        PYTHON_VERSION: 3.10.12
        PYTHON_MAJOR: "3.10"
    shm_size: '16gb'
    ulimits:
      memlock: -1
      stack: 67108864
    working_dir: /workspace
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
      - poetry-cache:/root/.cache/pypoetry
      - /mnt/st2:/workspace/datasets

    environment:
        ENV: "dev"
        TZ: "Asia/Tokyo"
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
        DEVICE: "gpu"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    command: bash

volumes:
  poetry-cache: